apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260523-200248-u0gx6qwod0vd-service
spec:
  selector:
    app: enterprise-system-20260523-200248-u0gx6qwod0vd
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
